version: '3.4'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=Library;Username=postgres;Password=Askerok2006;
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Askerok2006
      - POSTGRES_DB=Library
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
